name: flutter_desk_calendar
description: A Flutter UI widget that supports week, month, and month detail modes.
version: 0.0.1
homepage: https://github.com/xmq479361/FlutterCalendar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
